services:
 ubuntu_dev:
   tty: true
   image: ubuntu:latest
  # ports:
  #   - "25565:25565"
   environment:
     - DISPLAY=${HOSTNAME}:0
   volumes:
     - "/Users/josephmcilvaine:/mnt"
     - /tmp/.X11-unix:/tmp/.X11-unix