#include <boost/test/unit_test.hpp>
#include "Cpu.h"
#include <iostream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "Memory.h"
#include <boost/log/core.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/expressions.hpp>
#define CPU gbc::Cpu::Instance()
using namespace gbc;

// TESTS WERE AUTO GENERATED
// Test JSON taken from https://github.com/raddad772/jsmoo/tree/main/misc/tests/GeneratedTests/sm83

// test cases are repetitive, use a macro
#define MAKE_CPU_TEST(filepath, opcode) \
BOOST_AUTO_TEST_CASE(opcode) \
{ \
	boost::property_tree::ptree pt; \
	boost::property_tree::read_json(filepath, pt); \
	for(auto& a : pt) \
	{ \
		Expected e; \
		SetInitialParams(a); \
		SetExpectedParams(a, e); \
		CPU->Execute(); \
		CheckFinalState(e, a); \
	} \
}

void initlog()
{
	boost::log::core::get()->set_filter
    (
        boost::log::trivial::severity >= boost::log::trivial::error
    );
}
struct Expected
{
    Expected()
    {

    }
    register8_t a;
    register8_t b;
    register8_t c;
    register8_t d;
    register8_t e;
    register8_t f;
    register8_t h;
    register8_t l;
    address16_t pc;
    address16_t sp;
    std::array<uint16_t, 0xFFFF> memory = {};
};

void SetInitialParams(boost::property_tree::ptree::value_type& a)
{
	initlog(); // turns out logging for 500 tests is slow
   // gbc::Ram::Instance()->ClearMem();
   // std::cout << a.second.get<std::string>("name") << std::endl;
   // std::cout << a.second.get<unsigned short>("initial.pc") << std::endl;
    CPU->PC->Set(a.second.get<unsigned short>("initial.pc"));
    CPU->SP->Set(a.second.get<unsigned short>("initial.sp"));
    CPU->A->Set(a.second.get<unsigned char>("initial.a"));
    CPU->B->Set(a.second.get<unsigned short>("initial.b"));
    CPU->C->Set(a.second.get<unsigned short>("initial.c"));
    CPU->D->Set(a.second.get<unsigned short>("initial.d"));
    CPU->E->Set(a.second.get<unsigned short>("initial.e"));
    CPU->FLAGS->Set(a.second.get<unsigned char>("initial.f"));
    CPU->H->Set(a.second.get<unsigned short>("initial.h"));
    CPU->L->Set(a.second.get<unsigned short>("initial.l"));
    auto e = a.second.get_child("initial.ram");
    for (auto& x : e)
    {
        uint16_t addr = std::stoi(x.second.front().second.data());
        uint8_t val = std::stoi(x.second.back().second.data());
        gbc::Ram::Instance()->WriteByte(addr, val);
    }
    //  std::cout << "ram=" << e << std::endl;

}

void SetExpectedParams(boost::property_tree::ptree::value_type& a, Expected& e)
{
    //std::cout << a.second.get<std::string>("name") << std::endl;

    e.pc.Set(a.second.get<unsigned short>("final.pc"));
    e.sp.Set(a.second.get<unsigned short>("final.sp"));
    e.a.Set(a.second.get<unsigned char>("final.a"));
    e.b.Set(a.second.get<unsigned char>("final.b"));
    e.c.Set(a.second.get<unsigned char>("final.c"));
    e.d.Set(a.second.get<unsigned char>("final.d"));
    e.e.Set(a.second.get<unsigned char>("final.e"));
    e.f.Set(a.second.get<unsigned char>("final.f"));
    e.h.Set(a.second.get<unsigned char>("final.h"));
    e.l.Set(a.second.get<unsigned char>("final.l"));
    auto k = a.second.get_child("final.ram");
    for (auto& x : k)
    {
        uint16_t addr = std::stoi(x.second.front().second.data());
        uint8_t val = std::stoi(x.second.back().second.data());
        e.memory[addr] = val;
    }
}

void CheckFinalState(const Expected& e, const boost::property_tree::ptree::value_type& a)
{
    BOOST_CHECK_EQUAL(CPU->PC->value() , e.pc.value());
    BOOST_CHECK_EQUAL(CPU->SP->value() , e.sp.value());
    BOOST_CHECK_EQUAL(CPU->A->value() , e.a.value());
    BOOST_CHECK_EQUAL(CPU->B->value() , e.b.value());
    BOOST_CHECK_EQUAL(CPU->C->value() , e.c.value());
    BOOST_CHECK_EQUAL(CPU->D->value() , e.d.value());
    BOOST_CHECK_EQUAL(CPU->E->value() , e.e.value());
    BOOST_CHECK_EQUAL(CPU->FLAGS->value() , e.f.value());
    BOOST_CHECK_EQUAL(CPU->H->value() , e.h.value());
    BOOST_CHECK_EQUAL(CPU->L->value() , e.l.value());
	auto k = a.second.get_child("final.ram");
    for (auto& x : k)
    {
        uint16_t addr = std::stoi(x.second.front().second.data());
        uint8_t val = std::stoi(x.second.back().second.data());
		BOOST_LOG_TRIVIAL(debug) << "checking address " << addr << std::endl;
		BOOST_CHECK_EQUAL(e.memory[addr], gbc::Ram::Instance()->ReadByte(addr));
    }
}

// Each json file contains many test cases with initial and expected values for registers and memory
MAKE_CPU_TEST("../tests/v1/cb 3e.json",cpu_opcode_CB3E)
MAKE_CPU_TEST("../tests/v1/3d.json",cpu_opcode_3D)
MAKE_CPU_TEST("../tests/v1/fe.json",cpu_opcode_FE)
MAKE_CPU_TEST("../tests/v1/7c.json",cpu_opcode_7C)
MAKE_CPU_TEST("../tests/v1/cb ea.json",cpu_opcode_CBEA)
MAKE_CPU_TEST("../tests/v1/49.json",cpu_opcode_49)
MAKE_CPU_TEST("../tests/v1/27.json",cpu_opcode_27)
MAKE_CPU_TEST("../tests/v1/44.json",cpu_opcode_44)
MAKE_CPU_TEST("../tests/v1/cb a6.json",cpu_opcode_CBA6)
MAKE_CPU_TEST("../tests/v1/83.json",cpu_opcode_83)
MAKE_CPU_TEST("../tests/v1/38.json",cpu_opcode_38)
MAKE_CPU_TEST("../tests/v1/17.json",cpu_opcode_17)
MAKE_CPU_TEST("../tests/v1/d5.json",cpu_opcode_D5)
MAKE_CPU_TEST("../tests/v1/cb 04.json",cpu_opcode_CB04)
MAKE_CPU_TEST("../tests/v1/d2.json",cpu_opcode_D2)
MAKE_CPU_TEST("../tests/v1/4c.json",cpu_opcode_4C)
MAKE_CPU_TEST("../tests/v1/cb 6f.json",cpu_opcode_CB6F)
MAKE_CPU_TEST("../tests/v1/cb 9e.json",cpu_opcode_CB9E)
MAKE_CPU_TEST("../tests/v1/cb 52.json",cpu_opcode_CB52)
MAKE_CPU_TEST("../tests/v1/51.json",cpu_opcode_51)
MAKE_CPU_TEST("../tests/v1/cb e6.json",cpu_opcode_CBE6)
MAKE_CPU_TEST("../tests/v1/10.json",cpu_opcode_10)
MAKE_CPU_TEST("../tests/v1/cb b6.json",cpu_opcode_CBB6)
MAKE_CPU_TEST("../tests/v1/cb 60.json",cpu_opcode_CB60)
MAKE_CPU_TEST("../tests/v1/cb a2.json",cpu_opcode_CBA2)
MAKE_CPU_TEST("../tests/v1/82.json",cpu_opcode_82)
MAKE_CPU_TEST("../tests/v1/cb 25.json",cpu_opcode_CB25)
MAKE_CPU_TEST("../tests/v1/00.json",cpu_opcode_00)
MAKE_CPU_TEST("../tests/v1/ae.json",cpu_opcode_AE)
MAKE_CPU_TEST("../tests/v1/1b.json",cpu_opcode_1B)
MAKE_CPU_TEST("../tests/v1/cb 10.json",cpu_opcode_CB10)
MAKE_CPU_TEST("../tests/v1/de.json",cpu_opcode_DE)
MAKE_CPU_TEST("../tests/v1/21.json",cpu_opcode_21)
MAKE_CPU_TEST("../tests/v1/5f.json",cpu_opcode_5F)
MAKE_CPU_TEST("../tests/v1/cb 0e.json",cpu_opcode_CB0E)
MAKE_CPU_TEST("../tests/v1/81.json",cpu_opcode_81)
MAKE_CPU_TEST("../tests/v1/cb 9f.json",cpu_opcode_CB9F)
MAKE_CPU_TEST("../tests/v1/cb 5f.json",cpu_opcode_CB5F)
MAKE_CPU_TEST("../tests/v1/cb 2a.json",cpu_opcode_CB2A)
MAKE_CPU_TEST("../tests/v1/85.json",cpu_opcode_85)
MAKE_CPU_TEST("../tests/v1/cb cb.json",cpu_opcode_CBCB)
MAKE_CPU_TEST("../tests/v1/91.json",cpu_opcode_91)
MAKE_CPU_TEST("../tests/v1/a7.json",cpu_opcode_A7)
MAKE_CPU_TEST("../tests/v1/cb d3.json",cpu_opcode_CBD3)
MAKE_CPU_TEST("../tests/v1/28.json",cpu_opcode_28)
MAKE_CPU_TEST("../tests/v1/cb 8c.json",cpu_opcode_CB8C)
MAKE_CPU_TEST("../tests/v1/ef.json",cpu_opcode_EF)
MAKE_CPU_TEST("../tests/v1/cb 2f.json",cpu_opcode_CB2F)
MAKE_CPU_TEST("../tests/v1/cb b1.json",cpu_opcode_CBB1)
MAKE_CPU_TEST("../tests/v1/cb 03.json",cpu_opcode_CB03)
MAKE_CPU_TEST("../tests/v1/40.json",cpu_opcode_40)
MAKE_CPU_TEST("../tests/v1/d7.json",cpu_opcode_D7)
MAKE_CPU_TEST("../tests/v1/7e.json",cpu_opcode_7E)
MAKE_CPU_TEST("../tests/v1/4d.json",cpu_opcode_4D)
MAKE_CPU_TEST("../tests/v1/cb 54.json",cpu_opcode_CB54)
MAKE_CPU_TEST("../tests/v1/cb 41.json",cpu_opcode_CB41)
MAKE_CPU_TEST("../tests/v1/ff.json",cpu_opcode_FF)
MAKE_CPU_TEST("../tests/v1/cb f5.json",cpu_opcode_CBF5)
MAKE_CPU_TEST("../tests/v1/9d.json",cpu_opcode_9D)
MAKE_CPU_TEST("../tests/v1/b3.json",cpu_opcode_B3)
MAKE_CPU_TEST("../tests/v1/88.json",cpu_opcode_88)
MAKE_CPU_TEST("../tests/v1/45.json",cpu_opcode_45)
MAKE_CPU_TEST("../tests/v1/59.json",cpu_opcode_59)
MAKE_CPU_TEST("../tests/v1/ad.json",cpu_opcode_AD)
MAKE_CPU_TEST("../tests/v1/cb 8a.json",cpu_opcode_CB8A)
MAKE_CPU_TEST("../tests/v1/cb 9c.json",cpu_opcode_CB9C)
MAKE_CPU_TEST("../tests/v1/cb ef.json",cpu_opcode_CBEF)
MAKE_CPU_TEST("../tests/v1/cb 90.json",cpu_opcode_CB90)
MAKE_CPU_TEST("../tests/v1/c3.json",cpu_opcode_C3)
MAKE_CPU_TEST("../tests/v1/cb cf.json",cpu_opcode_CBCF)
MAKE_CPU_TEST("../tests/v1/2a.json",cpu_opcode_2A)
MAKE_CPU_TEST("../tests/v1/cb 33.json",cpu_opcode_CB33)
MAKE_CPU_TEST("../tests/v1/cb df.json",cpu_opcode_CBDF)
MAKE_CPU_TEST("../tests/v1/cb b0.json",cpu_opcode_CBB0)
MAKE_CPU_TEST("../tests/v1/87.json",cpu_opcode_87)
MAKE_CPU_TEST("../tests/v1/2c.json",cpu_opcode_2C)
MAKE_CPU_TEST("../tests/v1/4a.json",cpu_opcode_4A)
MAKE_CPU_TEST("../tests/v1/cb f7.json",cpu_opcode_CBF7)
MAKE_CPU_TEST("../tests/v1/cb f1.json",cpu_opcode_CBF1)
MAKE_CPU_TEST("../tests/v1/cb 26.json",cpu_opcode_CB26)
MAKE_CPU_TEST("../tests/v1/cb f3.json",cpu_opcode_CBF3)
MAKE_CPU_TEST("../tests/v1/cb 67.json",cpu_opcode_CB67)
MAKE_CPU_TEST("../tests/v1/32.json",cpu_opcode_32)
MAKE_CPU_TEST("../tests/v1/cb d8.json",cpu_opcode_CBD8)
MAKE_CPU_TEST("../tests/v1/cb ac.json",cpu_opcode_CBAC)
MAKE_CPU_TEST("../tests/v1/9b.json",cpu_opcode_9B)
MAKE_CPU_TEST("../tests/v1/cb 77.json",cpu_opcode_CB77)
MAKE_CPU_TEST("../tests/v1/cb a3.json",cpu_opcode_CBA3)
MAKE_CPU_TEST("../tests/v1/0b.json",cpu_opcode_0B)
MAKE_CPU_TEST("../tests/v1/22.json",cpu_opcode_22)
MAKE_CPU_TEST("../tests/v1/90.json",cpu_opcode_90)
MAKE_CPU_TEST("../tests/v1/cb c4.json",cpu_opcode_CBC4)
MAKE_CPU_TEST("../tests/v1/3b.json",cpu_opcode_3B)
MAKE_CPU_TEST("../tests/v1/1c.json",cpu_opcode_1C)
MAKE_CPU_TEST("../tests/v1/cb 91.json",cpu_opcode_CB91)
MAKE_CPU_TEST("../tests/v1/f7.json",cpu_opcode_F7)
MAKE_CPU_TEST("../tests/v1/cb 55.json",cpu_opcode_CB55)
MAKE_CPU_TEST("../tests/v1/cb 6d.json",cpu_opcode_CB6D)
MAKE_CPU_TEST("../tests/v1/cb 11.json",cpu_opcode_CB11)
MAKE_CPU_TEST("../tests/v1/75.json",cpu_opcode_75)
MAKE_CPU_TEST("../tests/v1/e2.json",cpu_opcode_E2)
MAKE_CPU_TEST("../tests/v1/cb ab.json",cpu_opcode_CBAB)
MAKE_CPU_TEST("../tests/v1/6f.json",cpu_opcode_6F)
MAKE_CPU_TEST("../tests/v1/cb b9.json",cpu_opcode_CBB9)
MAKE_CPU_TEST("../tests/v1/a2.json",cpu_opcode_A2)
MAKE_CPU_TEST("../tests/v1/cb 74.json",cpu_opcode_CB74)
MAKE_CPU_TEST("../tests/v1/4f.json",cpu_opcode_4F)
MAKE_CPU_TEST("../tests/v1/f9.json",cpu_opcode_F9)
MAKE_CPU_TEST("../tests/v1/cb 06.json",cpu_opcode_CB06)
MAKE_CPU_TEST("../tests/v1/cb a7.json",cpu_opcode_CBA7)
MAKE_CPU_TEST("../tests/v1/cb 63.json",cpu_opcode_CB63)
MAKE_CPU_TEST("../tests/v1/cb 8f.json",cpu_opcode_CB8F)
MAKE_CPU_TEST("../tests/v1/cb 1b.json",cpu_opcode_CB1B)
MAKE_CPU_TEST("../tests/v1/66.json",cpu_opcode_66)
MAKE_CPU_TEST("../tests/v1/cb f6.json",cpu_opcode_CBF6)
MAKE_CPU_TEST("../tests/v1/cb 36.json",cpu_opcode_CB36)
MAKE_CPU_TEST("../tests/v1/ca.json",cpu_opcode_CA)
MAKE_CPU_TEST("../tests/v1/cb 4d.json",cpu_opcode_CB4D)
MAKE_CPU_TEST("../tests/v1/cb 12.json",cpu_opcode_CB12)
MAKE_CPU_TEST("../tests/v1/48.json",cpu_opcode_48)
MAKE_CPU_TEST("../tests/v1/98.json",cpu_opcode_98)
MAKE_CPU_TEST("../tests/v1/cb 88.json",cpu_opcode_CB88)
MAKE_CPU_TEST("../tests/v1/46.json",cpu_opcode_46)
MAKE_CPU_TEST("../tests/v1/cb fb.json",cpu_opcode_CBFB)
MAKE_CPU_TEST("../tests/v1/cb b2.json",cpu_opcode_CBB2)
MAKE_CPU_TEST("../tests/v1/ac.json",cpu_opcode_AC)
MAKE_CPU_TEST("../tests/v1/30.json",cpu_opcode_30)
MAKE_CPU_TEST("../tests/v1/cb 8b.json",cpu_opcode_CB8B)
MAKE_CPU_TEST("../tests/v1/96.json",cpu_opcode_96)
MAKE_CPU_TEST("../tests/v1/cb ff.json",cpu_opcode_CBFF)
MAKE_CPU_TEST("../tests/v1/cb 09.json",cpu_opcode_CB09)
MAKE_CPU_TEST("../tests/v1/b7.json",cpu_opcode_B7)
MAKE_CPU_TEST("../tests/v1/b4.json",cpu_opcode_B4)
MAKE_CPU_TEST("../tests/v1/54.json",cpu_opcode_54)
MAKE_CPU_TEST("../tests/v1/cb 1d.json",cpu_opcode_CB1D)
MAKE_CPU_TEST("../tests/v1/cb 1f.json",cpu_opcode_CB1F)
MAKE_CPU_TEST("../tests/v1/c7.json",cpu_opcode_C7)
MAKE_CPU_TEST("../tests/v1/19.json",cpu_opcode_19)
MAKE_CPU_TEST("../tests/v1/d4.json",cpu_opcode_D4)
MAKE_CPU_TEST("../tests/v1/6b.json",cpu_opcode_6B)
MAKE_CPU_TEST("../tests/v1/cb d9.json",cpu_opcode_CBD9)
MAKE_CPU_TEST("../tests/v1/ce.json",cpu_opcode_CE)
MAKE_CPU_TEST("../tests/v1/e8.json",cpu_opcode_E8)
MAKE_CPU_TEST("../tests/v1/69.json",cpu_opcode_69)
MAKE_CPU_TEST("../tests/v1/9c.json",cpu_opcode_9C)
MAKE_CPU_TEST("../tests/v1/cb b5.json",cpu_opcode_CBB5)
MAKE_CPU_TEST("../tests/v1/d1.json",cpu_opcode_D1)
MAKE_CPU_TEST("../tests/v1/cb dc.json",cpu_opcode_CBDC)
MAKE_CPU_TEST("../tests/v1/93.json",cpu_opcode_93)
MAKE_CPU_TEST("../tests/v1/cb 7d.json",cpu_opcode_CB7D)
MAKE_CPU_TEST("../tests/v1/cb 23.json",cpu_opcode_CB23)
MAKE_CPU_TEST("../tests/v1/b6.json",cpu_opcode_B6)
MAKE_CPU_TEST("../tests/v1/cb 57.json",cpu_opcode_CB57)
MAKE_CPU_TEST("../tests/v1/c9.json",cpu_opcode_C9)
MAKE_CPU_TEST("../tests/v1/cb 02.json",cpu_opcode_CB02)
MAKE_CPU_TEST("../tests/v1/cb 96.json",cpu_opcode_CB96)
MAKE_CPU_TEST("../tests/v1/53.json",cpu_opcode_53)
MAKE_CPU_TEST("../tests/v1/cb fd.json",cpu_opcode_CBFD)
MAKE_CPU_TEST("../tests/v1/2d.json",cpu_opcode_2D)
MAKE_CPU_TEST("../tests/v1/cb 42.json",cpu_opcode_CB42)
MAKE_CPU_TEST("../tests/v1/cb 71.json",cpu_opcode_CB71)
MAKE_CPU_TEST("../tests/v1/55.json",cpu_opcode_55)
MAKE_CPU_TEST("../tests/v1/c1.json",cpu_opcode_C1)
MAKE_CPU_TEST("../tests/v1/cb 72.json",cpu_opcode_CB72)
MAKE_CPU_TEST("../tests/v1/df.json",cpu_opcode_DF)
MAKE_CPU_TEST("../tests/v1/cb 99.json",cpu_opcode_CB99)
MAKE_CPU_TEST("../tests/v1/cb 80.json",cpu_opcode_CB80)
MAKE_CPU_TEST("../tests/v1/a9.json",cpu_opcode_A9)
MAKE_CPU_TEST("../tests/v1/cb e0.json",cpu_opcode_CBE0)
MAKE_CPU_TEST("../tests/v1/e6.json",cpu_opcode_E6)
MAKE_CPU_TEST("../tests/v1/0e.json",cpu_opcode_0E)
MAKE_CPU_TEST("../tests/v1/cb 01.json",cpu_opcode_CB01)
MAKE_CPU_TEST("../tests/v1/e0.json",cpu_opcode_E0)
MAKE_CPU_TEST("../tests/v1/cb fa.json",cpu_opcode_CBFA)
MAKE_CPU_TEST("../tests/v1/6c.json",cpu_opcode_6C)
MAKE_CPU_TEST("../tests/v1/cb 69.json",cpu_opcode_CB69)
MAKE_CPU_TEST("../tests/v1/1f.json",cpu_opcode_1F)
MAKE_CPU_TEST("../tests/v1/cb 86.json",cpu_opcode_CB86)
MAKE_CPU_TEST("../tests/v1/cb 28.json",cpu_opcode_CB28)
MAKE_CPU_TEST("../tests/v1/37.json",cpu_opcode_37)
MAKE_CPU_TEST("../tests/v1/cb 53.json",cpu_opcode_CB53)
MAKE_CPU_TEST("../tests/v1/cb 2e.json",cpu_opcode_CB2E)
MAKE_CPU_TEST("../tests/v1/cb be.json",cpu_opcode_CBBE)
MAKE_CPU_TEST("../tests/v1/cf.json",cpu_opcode_CF)
MAKE_CPU_TEST("../tests/v1/f0.json",cpu_opcode_F0)
MAKE_CPU_TEST("../tests/v1/cb 89.json",cpu_opcode_CB89)
MAKE_CPU_TEST("../tests/v1/cb 59.json",cpu_opcode_CB59)
MAKE_CPU_TEST("../tests/v1/cb ae.json",cpu_opcode_CBAE)
MAKE_CPU_TEST("../tests/v1/cb e2.json",cpu_opcode_CBE2)
MAKE_CPU_TEST("../tests/v1/cb d0.json",cpu_opcode_CBD0)
MAKE_CPU_TEST("../tests/v1/cb c6.json",cpu_opcode_CBC6)
MAKE_CPU_TEST("../tests/v1/cb 38.json",cpu_opcode_CB38)
MAKE_CPU_TEST("../tests/v1/71.json",cpu_opcode_71)
MAKE_CPU_TEST("../tests/v1/cb f8.json",cpu_opcode_CBF8)
MAKE_CPU_TEST("../tests/v1/a6.json",cpu_opcode_A6)
MAKE_CPU_TEST("../tests/v1/5e.json",cpu_opcode_5E)
MAKE_CPU_TEST("../tests/v1/13.json",cpu_opcode_13)
MAKE_CPU_TEST("../tests/v1/89.json",cpu_opcode_89)
MAKE_CPU_TEST("../tests/v1/b9.json",cpu_opcode_B9)
MAKE_CPU_TEST("../tests/v1/cb 3a.json",cpu_opcode_CB3A)
MAKE_CPU_TEST("../tests/v1/cb f2.json",cpu_opcode_CBF2)
MAKE_CPU_TEST("../tests/v1/cb 35.json",cpu_opcode_CB35)
MAKE_CPU_TEST("../tests/v1/cb 19.json",cpu_opcode_CB19)
MAKE_CPU_TEST("../tests/v1/cb cd.json",cpu_opcode_CBCD)
MAKE_CPU_TEST("../tests/v1/5d.json",cpu_opcode_5D)
MAKE_CPU_TEST("../tests/v1/7b.json",cpu_opcode_7B)
MAKE_CPU_TEST("../tests/v1/e9.json",cpu_opcode_E9)
MAKE_CPU_TEST("../tests/v1/cb 6b.json",cpu_opcode_CB6B)
MAKE_CPU_TEST("../tests/v1/3a.json",cpu_opcode_3A)
MAKE_CPU_TEST("../tests/v1/0c.json",cpu_opcode_0C)
MAKE_CPU_TEST("../tests/v1/cb ba.json",cpu_opcode_CBBA)
MAKE_CPU_TEST("../tests/v1/cb 4f.json",cpu_opcode_CB4F)
MAKE_CPU_TEST("../tests/v1/cb 3c.json",cpu_opcode_CB3C)
MAKE_CPU_TEST("../tests/v1/d9.json",cpu_opcode_D9)
MAKE_CPU_TEST("../tests/v1/60.json",cpu_opcode_60)
MAKE_CPU_TEST("../tests/v1/bc.json",cpu_opcode_BC)
MAKE_CPU_TEST("../tests/v1/cb 7c.json",cpu_opcode_CB7C)
MAKE_CPU_TEST("../tests/v1/cb c7.json",cpu_opcode_CBC7)
MAKE_CPU_TEST("../tests/v1/7f.json",cpu_opcode_7F)
MAKE_CPU_TEST("../tests/v1/cb 0a.json",cpu_opcode_CB0A)
MAKE_CPU_TEST("../tests/v1/cb c3.json",cpu_opcode_CBC3)
MAKE_CPU_TEST("../tests/v1/04.json",cpu_opcode_04)
MAKE_CPU_TEST("../tests/v1/97.json",cpu_opcode_97)
MAKE_CPU_TEST("../tests/v1/cb 22.json",cpu_opcode_CB22)
MAKE_CPU_TEST("../tests/v1/72.json",cpu_opcode_72)
MAKE_CPU_TEST("../tests/v1/f3.json",cpu_opcode_F3)
MAKE_CPU_TEST("../tests/v1/cb 16.json",cpu_opcode_CB16)
MAKE_CPU_TEST("../tests/v1/9a.json",cpu_opcode_9A)
MAKE_CPU_TEST("../tests/v1/cb 2c.json",cpu_opcode_CB2C)
MAKE_CPU_TEST("../tests/v1/cb ca.json",cpu_opcode_CBCA)
MAKE_CPU_TEST("../tests/v1/cb 9a.json",cpu_opcode_CB9A)
MAKE_CPU_TEST("../tests/v1/cb 56.json",cpu_opcode_CB56)
MAKE_CPU_TEST("../tests/v1/cb d1.json",cpu_opcode_CBD1)
MAKE_CPU_TEST("../tests/v1/07.json",cpu_opcode_07)
MAKE_CPU_TEST("../tests/v1/cb 6a.json",cpu_opcode_CB6A)
MAKE_CPU_TEST("../tests/v1/cd.json",cpu_opcode_CD)
MAKE_CPU_TEST("../tests/v1/09.json",cpu_opcode_09)
MAKE_CPU_TEST("../tests/v1/cb 85.json",cpu_opcode_CB85)
MAKE_CPU_TEST("../tests/v1/c4.json",cpu_opcode_C4)
MAKE_CPU_TEST("../tests/v1/cb ed.json",cpu_opcode_CBED)
MAKE_CPU_TEST("../tests/v1/cb 31.json",cpu_opcode_CB31)
MAKE_CPU_TEST("../tests/v1/0a.json",cpu_opcode_0A)
MAKE_CPU_TEST("../tests/v1/cb 64.json",cpu_opcode_CB64)
MAKE_CPU_TEST("../tests/v1/cb 30.json",cpu_opcode_CB30)
MAKE_CPU_TEST("../tests/v1/05.json",cpu_opcode_05)
MAKE_CPU_TEST("../tests/v1/b1.json",cpu_opcode_B1)
MAKE_CPU_TEST("../tests/v1/cb 68.json",cpu_opcode_CB68)
MAKE_CPU_TEST("../tests/v1/63.json",cpu_opcode_63)
MAKE_CPU_TEST("../tests/v1/cb b8.json",cpu_opcode_CBB8)
MAKE_CPU_TEST("../tests/v1/3f.json",cpu_opcode_3F)
MAKE_CPU_TEST("../tests/v1/0f.json",cpu_opcode_0F)
MAKE_CPU_TEST("../tests/v1/3c.json",cpu_opcode_3C)
MAKE_CPU_TEST("../tests/v1/65.json",cpu_opcode_65)
MAKE_CPU_TEST("../tests/v1/cb 5d.json",cpu_opcode_CB5D)
MAKE_CPU_TEST("../tests/v1/d6.json",cpu_opcode_D6)
MAKE_CPU_TEST("../tests/v1/fb.json",cpu_opcode_FB)
MAKE_CPU_TEST("../tests/v1/cb 7e.json",cpu_opcode_CB7E)
MAKE_CPU_TEST("../tests/v1/cb 34.json",cpu_opcode_CB34)
MAKE_CPU_TEST("../tests/v1/c2.json",cpu_opcode_C2)
MAKE_CPU_TEST("../tests/v1/cb 87.json",cpu_opcode_CB87)
MAKE_CPU_TEST("../tests/v1/cb 84.json",cpu_opcode_CB84)
MAKE_CPU_TEST("../tests/v1/cb 51.json",cpu_opcode_CB51)
MAKE_CPU_TEST("../tests/v1/73.json",cpu_opcode_73)
MAKE_CPU_TEST("../tests/v1/cb fe.json",cpu_opcode_CBFE)
MAKE_CPU_TEST("../tests/v1/cb a0.json",cpu_opcode_CBA0)
MAKE_CPU_TEST("../tests/v1/cb d4.json",cpu_opcode_CBD4)
MAKE_CPU_TEST("../tests/v1/cb 7a.json",cpu_opcode_CB7A)
MAKE_CPU_TEST("../tests/v1/cb aa.json",cpu_opcode_CBAA)
MAKE_CPU_TEST("../tests/v1/6e.json",cpu_opcode_6E)
MAKE_CPU_TEST("../tests/v1/cb 58.json",cpu_opcode_CB58)
MAKE_CPU_TEST("../tests/v1/50.json",cpu_opcode_50)
MAKE_CPU_TEST("../tests/v1/35.json",cpu_opcode_35)
MAKE_CPU_TEST("../tests/v1/16.json",cpu_opcode_16)
MAKE_CPU_TEST("../tests/v1/cb 9d.json",cpu_opcode_CB9D)
MAKE_CPU_TEST("../tests/v1/cb e5.json",cpu_opcode_CBE5)
MAKE_CPU_TEST("../tests/v1/cb 24.json",cpu_opcode_CB24)
MAKE_CPU_TEST("../tests/v1/86.json",cpu_opcode_86)
MAKE_CPU_TEST("../tests/v1/ab.json",cpu_opcode_AB)
MAKE_CPU_TEST("../tests/v1/cb a8.json",cpu_opcode_CBA8)
MAKE_CPU_TEST("../tests/v1/9f.json",cpu_opcode_9F)
MAKE_CPU_TEST("../tests/v1/cb b3.json",cpu_opcode_CBB3)
MAKE_CPU_TEST("../tests/v1/cb 37.json",cpu_opcode_CB37)
MAKE_CPU_TEST("../tests/v1/cb 29.json",cpu_opcode_CB29)
MAKE_CPU_TEST("../tests/v1/3e.json",cpu_opcode_3E)
MAKE_CPU_TEST("../tests/v1/cb 76.json",cpu_opcode_CB76)
MAKE_CPU_TEST("../tests/v1/94.json",cpu_opcode_94)
MAKE_CPU_TEST("../tests/v1/cb 7f.json",cpu_opcode_CB7F)
MAKE_CPU_TEST("../tests/v1/76.json",cpu_opcode_76)
MAKE_CPU_TEST("../tests/v1/d8.json",cpu_opcode_D8)
MAKE_CPU_TEST("../tests/v1/cb a4.json",cpu_opcode_CBA4)
MAKE_CPU_TEST("../tests/v1/cb ad.json",cpu_opcode_CBAD)
MAKE_CPU_TEST("../tests/v1/cb cc.json",cpu_opcode_CBCC)
MAKE_CPU_TEST("../tests/v1/67.json",cpu_opcode_67)
MAKE_CPU_TEST("../tests/v1/cb 92.json",cpu_opcode_CB92)
MAKE_CPU_TEST("../tests/v1/a3.json",cpu_opcode_A3)
MAKE_CPU_TEST("../tests/v1/cb 95.json",cpu_opcode_CB95)
MAKE_CPU_TEST("../tests/v1/25.json",cpu_opcode_25)
MAKE_CPU_TEST("../tests/v1/cb 49.json",cpu_opcode_CB49)
MAKE_CPU_TEST("../tests/v1/14.json",cpu_opcode_14)
MAKE_CPU_TEST("../tests/v1/cb 78.json",cpu_opcode_CB78)
MAKE_CPU_TEST("../tests/v1/64.json",cpu_opcode_64)
MAKE_CPU_TEST("../tests/v1/33.json",cpu_opcode_33)
MAKE_CPU_TEST("../tests/v1/cb 9b.json",cpu_opcode_CB9B)
MAKE_CPU_TEST("../tests/v1/cb 15.json",cpu_opcode_CB15)
MAKE_CPU_TEST("../tests/v1/62.json",cpu_opcode_62)
MAKE_CPU_TEST("../tests/v1/15.json",cpu_opcode_15)
MAKE_CPU_TEST("../tests/v1/cb 05.json",cpu_opcode_CB05)
MAKE_CPU_TEST("../tests/v1/74.json",cpu_opcode_74)
MAKE_CPU_TEST("../tests/v1/cb a1.json",cpu_opcode_CBA1)
MAKE_CPU_TEST("../tests/v1/cb de.json",cpu_opcode_CBDE)
MAKE_CPU_TEST("../tests/v1/da.json",cpu_opcode_DA)
MAKE_CPU_TEST("../tests/v1/2e.json",cpu_opcode_2E)
MAKE_CPU_TEST("../tests/v1/79.json",cpu_opcode_79)
MAKE_CPU_TEST("../tests/v1/12.json",cpu_opcode_12)
MAKE_CPU_TEST("../tests/v1/cb 40.json",cpu_opcode_CB40)
MAKE_CPU_TEST("../tests/v1/1e.json",cpu_opcode_1E)
MAKE_CPU_TEST("../tests/v1/9e.json",cpu_opcode_9E)
MAKE_CPU_TEST("../tests/v1/cb 1a.json",cpu_opcode_CB1A)
MAKE_CPU_TEST("../tests/v1/cb 4a.json",cpu_opcode_CB4A)
MAKE_CPU_TEST("../tests/v1/cb 98.json",cpu_opcode_CB98)
MAKE_CPU_TEST("../tests/v1/cb 3f.json",cpu_opcode_CB3F)
MAKE_CPU_TEST("../tests/v1/5c.json",cpu_opcode_5C)
MAKE_CPU_TEST("../tests/v1/cb 44.json",cpu_opcode_CB44)
MAKE_CPU_TEST("../tests/v1/d0.json",cpu_opcode_D0)
MAKE_CPU_TEST("../tests/v1/e5.json",cpu_opcode_E5)
MAKE_CPU_TEST("../tests/v1/cb 32.json",cpu_opcode_CB32)
MAKE_CPU_TEST("../tests/v1/cb da.json",cpu_opcode_CBDA)
MAKE_CPU_TEST("../tests/v1/6a.json",cpu_opcode_6A)
MAKE_CPU_TEST("../tests/v1/cb 17.json",cpu_opcode_CB17)
MAKE_CPU_TEST("../tests/v1/23.json",cpu_opcode_23)
MAKE_CPU_TEST("../tests/v1/8d.json",cpu_opcode_8D)
MAKE_CPU_TEST("../tests/v1/cb c8.json",cpu_opcode_CBC8)
MAKE_CPU_TEST("../tests/v1/cb e7.json",cpu_opcode_CBE7)
MAKE_CPU_TEST("../tests/v1/cb ee.json",cpu_opcode_CBEE)
MAKE_CPU_TEST("../tests/v1/1a.json",cpu_opcode_1A)
MAKE_CPU_TEST("../tests/v1/cb 75.json",cpu_opcode_CB75)
MAKE_CPU_TEST("../tests/v1/cb 5a.json",cpu_opcode_CB5A)
MAKE_CPU_TEST("../tests/v1/cb d2.json",cpu_opcode_CBD2)
MAKE_CPU_TEST("../tests/v1/cb f0.json",cpu_opcode_CBF0)
MAKE_CPU_TEST("../tests/v1/cb c9.json",cpu_opcode_CBC9)
MAKE_CPU_TEST("../tests/v1/af.json",cpu_opcode_AF)
MAKE_CPU_TEST("../tests/v1/5a.json",cpu_opcode_5A)
MAKE_CPU_TEST("../tests/v1/cb e1.json",cpu_opcode_CBE1)
MAKE_CPU_TEST("../tests/v1/a5.json",cpu_opcode_A5)
MAKE_CPU_TEST("../tests/v1/cb 4e.json",cpu_opcode_CB4E)
MAKE_CPU_TEST("../tests/v1/cb 6e.json",cpu_opcode_CB6E)
MAKE_CPU_TEST("../tests/v1/cb e8.json",cpu_opcode_CBE8)
MAKE_CPU_TEST("../tests/v1/cb 73.json",cpu_opcode_CB73)
MAKE_CPU_TEST("../tests/v1/cb 94.json",cpu_opcode_CB94)
MAKE_CPU_TEST("../tests/v1/56.json",cpu_opcode_56)
MAKE_CPU_TEST("../tests/v1/cb 1c.json",cpu_opcode_CB1C)
MAKE_CPU_TEST("../tests/v1/01.json",cpu_opcode_01)
MAKE_CPU_TEST("../tests/v1/cb 62.json",cpu_opcode_CB62)
MAKE_CPU_TEST("../tests/v1/cb 70.json",cpu_opcode_CB70)
MAKE_CPU_TEST("../tests/v1/b2.json",cpu_opcode_B2)
MAKE_CPU_TEST("../tests/v1/cb dd.json",cpu_opcode_CBDD)
MAKE_CPU_TEST("../tests/v1/4e.json",cpu_opcode_4E)
MAKE_CPU_TEST("../tests/v1/cb 0b.json",cpu_opcode_CB0B)
MAKE_CPU_TEST("../tests/v1/c0.json",cpu_opcode_C0)
MAKE_CPU_TEST("../tests/v1/f2.json",cpu_opcode_F2)
MAKE_CPU_TEST("../tests/v1/f8.json",cpu_opcode_F8)
MAKE_CPU_TEST("../tests/v1/cb ce.json",cpu_opcode_CBCE)
MAKE_CPU_TEST("../tests/v1/36.json",cpu_opcode_36)
MAKE_CPU_TEST("../tests/v1/cb a9.json",cpu_opcode_CBA9)
MAKE_CPU_TEST("../tests/v1/cb 2b.json",cpu_opcode_CB2B)
MAKE_CPU_TEST("../tests/v1/dc.json",cpu_opcode_DC)
MAKE_CPU_TEST("../tests/v1/cc.json",cpu_opcode_CC)
MAKE_CPU_TEST("../tests/v1/31.json",cpu_opcode_31)
MAKE_CPU_TEST("../tests/v1/ee.json",cpu_opcode_EE)
MAKE_CPU_TEST("../tests/v1/61.json",cpu_opcode_61)
MAKE_CPU_TEST("../tests/v1/f5.json",cpu_opcode_F5)
MAKE_CPU_TEST("../tests/v1/cb d5.json",cpu_opcode_CBD5)
MAKE_CPU_TEST("../tests/v1/18.json",cpu_opcode_18)
MAKE_CPU_TEST("../tests/v1/e7.json",cpu_opcode_E7)
MAKE_CPU_TEST("../tests/v1/cb 97.json",cpu_opcode_CB97)
MAKE_CPU_TEST("../tests/v1/58.json",cpu_opcode_58)
MAKE_CPU_TEST("../tests/v1/8f.json",cpu_opcode_8F)
MAKE_CPU_TEST("../tests/v1/1d.json",cpu_opcode_1D)
MAKE_CPU_TEST("../tests/v1/cb 4c.json",cpu_opcode_CB4C)
MAKE_CPU_TEST("../tests/v1/99.json",cpu_opcode_99)
MAKE_CPU_TEST("../tests/v1/cb f9.json",cpu_opcode_CBF9)
MAKE_CPU_TEST("../tests/v1/cb 0c.json",cpu_opcode_CB0C)
MAKE_CPU_TEST("../tests/v1/cb e3.json",cpu_opcode_CBE3)
MAKE_CPU_TEST("../tests/v1/cb a5.json",cpu_opcode_CBA5)
MAKE_CPU_TEST("../tests/v1/77.json",cpu_opcode_77)
MAKE_CPU_TEST("../tests/v1/cb 83.json",cpu_opcode_CB83)
MAKE_CPU_TEST("../tests/v1/aa.json",cpu_opcode_AA)
MAKE_CPU_TEST("../tests/v1/cb 4b.json",cpu_opcode_CB4B)
MAKE_CPU_TEST("../tests/v1/42.json",cpu_opcode_42)
MAKE_CPU_TEST("../tests/v1/b0.json",cpu_opcode_B0)
MAKE_CPU_TEST("../tests/v1/20.json",cpu_opcode_20)
MAKE_CPU_TEST("../tests/v1/cb 3d.json",cpu_opcode_CB3D)
MAKE_CPU_TEST("../tests/v1/cb 18.json",cpu_opcode_CB18)
MAKE_CPU_TEST("../tests/v1/8b.json",cpu_opcode_8B)
MAKE_CPU_TEST("../tests/v1/cb 0d.json",cpu_opcode_CB0D)
MAKE_CPU_TEST("../tests/v1/cb 5e.json",cpu_opcode_CB5E)
MAKE_CPU_TEST("../tests/v1/cb c5.json",cpu_opcode_CBC5)
MAKE_CPU_TEST("../tests/v1/ba.json",cpu_opcode_BA)
MAKE_CPU_TEST("../tests/v1/8a.json",cpu_opcode_8A)
MAKE_CPU_TEST("../tests/v1/f6.json",cpu_opcode_F6)
MAKE_CPU_TEST("../tests/v1/02.json",cpu_opcode_02)
MAKE_CPU_TEST("../tests/v1/cb b7.json",cpu_opcode_CBB7)
MAKE_CPU_TEST("../tests/v1/7d.json",cpu_opcode_7D)
MAKE_CPU_TEST("../tests/v1/cb 45.json",cpu_opcode_CB45)
MAKE_CPU_TEST("../tests/v1/cb e4.json",cpu_opcode_CBE4)
MAKE_CPU_TEST("../tests/v1/43.json",cpu_opcode_43)
MAKE_CPU_TEST("../tests/v1/cb 66.json",cpu_opcode_CB66)
MAKE_CPU_TEST("../tests/v1/cb 6c.json",cpu_opcode_CB6C)
MAKE_CPU_TEST("../tests/v1/29.json",cpu_opcode_29)
MAKE_CPU_TEST("../tests/v1/c5.json",cpu_opcode_C5)
MAKE_CPU_TEST("../tests/v1/80.json",cpu_opcode_80)
MAKE_CPU_TEST("../tests/v1/cb 82.json",cpu_opcode_CB82)
MAKE_CPU_TEST("../tests/v1/cb 7b.json",cpu_opcode_CB7B)
MAKE_CPU_TEST("../tests/v1/cb 07.json",cpu_opcode_CB07)
MAKE_CPU_TEST("../tests/v1/0d.json",cpu_opcode_0D)
MAKE_CPU_TEST("../tests/v1/cb 61.json",cpu_opcode_CB61)
MAKE_CPU_TEST("../tests/v1/78.json",cpu_opcode_78)
MAKE_CPU_TEST("../tests/v1/8e.json",cpu_opcode_8E)
MAKE_CPU_TEST("../tests/v1/cb 08.json",cpu_opcode_CB08)
MAKE_CPU_TEST("../tests/v1/cb 65.json",cpu_opcode_CB65)
MAKE_CPU_TEST("../tests/v1/be.json",cpu_opcode_BE)
MAKE_CPU_TEST("../tests/v1/2f.json",cpu_opcode_2F)
MAKE_CPU_TEST("../tests/v1/cb 5b.json",cpu_opcode_CB5B)
MAKE_CPU_TEST("../tests/v1/8c.json",cpu_opcode_8C)
MAKE_CPU_TEST("../tests/v1/a8.json",cpu_opcode_A8)
MAKE_CPU_TEST("../tests/v1/cb 93.json",cpu_opcode_CB93)
MAKE_CPU_TEST("../tests/v1/cb bf.json",cpu_opcode_CBBF)
MAKE_CPU_TEST("../tests/v1/cb 0f.json",cpu_opcode_CB0F)
MAKE_CPU_TEST("../tests/v1/47.json",cpu_opcode_47)
MAKE_CPU_TEST("../tests/v1/08.json",cpu_opcode_08)
MAKE_CPU_TEST("../tests/v1/cb 39.json",cpu_opcode_CB39)
MAKE_CPU_TEST("../tests/v1/cb b4.json",cpu_opcode_CBB4)
MAKE_CPU_TEST("../tests/v1/95.json",cpu_opcode_95)
MAKE_CPU_TEST("../tests/v1/c6.json",cpu_opcode_C6)
MAKE_CPU_TEST("../tests/v1/ea.json",cpu_opcode_EA)
MAKE_CPU_TEST("../tests/v1/bd.json",cpu_opcode_BD)
MAKE_CPU_TEST("../tests/v1/cb 27.json",cpu_opcode_CB27)
MAKE_CPU_TEST("../tests/v1/b5.json",cpu_opcode_B5)
MAKE_CPU_TEST("../tests/v1/cb ec.json",cpu_opcode_CBEC)
MAKE_CPU_TEST("../tests/v1/a0.json",cpu_opcode_A0)
MAKE_CPU_TEST("../tests/v1/cb 50.json",cpu_opcode_CB50)
MAKE_CPU_TEST("../tests/v1/cb c2.json",cpu_opcode_CBC2)
MAKE_CPU_TEST("../tests/v1/cb 81.json",cpu_opcode_CB81)
MAKE_CPU_TEST("../tests/v1/57.json",cpu_opcode_57)
MAKE_CPU_TEST("../tests/v1/cb 79.json",cpu_opcode_CB79)
MAKE_CPU_TEST("../tests/v1/84.json",cpu_opcode_84)
MAKE_CPU_TEST("../tests/v1/24.json",cpu_opcode_24)
MAKE_CPU_TEST("../tests/v1/cb bc.json",cpu_opcode_CBBC)
MAKE_CPU_TEST("../tests/v1/03.json",cpu_opcode_03)
MAKE_CPU_TEST("../tests/v1/f1.json",cpu_opcode_F1)
MAKE_CPU_TEST("../tests/v1/cb 8d.json",cpu_opcode_CB8D)
MAKE_CPU_TEST("../tests/v1/39.json",cpu_opcode_39)
MAKE_CPU_TEST("../tests/v1/41.json",cpu_opcode_41)
MAKE_CPU_TEST("../tests/v1/c8.json",cpu_opcode_C8)
MAKE_CPU_TEST("../tests/v1/70.json",cpu_opcode_70)
MAKE_CPU_TEST("../tests/v1/bf.json",cpu_opcode_BF)
MAKE_CPU_TEST("../tests/v1/cb 14.json",cpu_opcode_CB14)
MAKE_CPU_TEST("../tests/v1/4b.json",cpu_opcode_4B)
MAKE_CPU_TEST("../tests/v1/cb 1e.json",cpu_opcode_CB1E)
MAKE_CPU_TEST("../tests/v1/11.json",cpu_opcode_11)
MAKE_CPU_TEST("../tests/v1/cb d7.json",cpu_opcode_CBD7)
MAKE_CPU_TEST("../tests/v1/e1.json",cpu_opcode_E1)
MAKE_CPU_TEST("../tests/v1/cb c1.json",cpu_opcode_CBC1)
MAKE_CPU_TEST("../tests/v1/cb 46.json",cpu_opcode_CB46)
MAKE_CPU_TEST("../tests/v1/68.json",cpu_opcode_68)
MAKE_CPU_TEST("../tests/v1/26.json",cpu_opcode_26)
MAKE_CPU_TEST("../tests/v1/cb 5c.json",cpu_opcode_CB5C)
MAKE_CPU_TEST("../tests/v1/cb f4.json",cpu_opcode_CBF4)
MAKE_CPU_TEST("../tests/v1/cb 21.json",cpu_opcode_CB21)
MAKE_CPU_TEST("../tests/v1/cb bd.json",cpu_opcode_CBBD)
MAKE_CPU_TEST("../tests/v1/92.json",cpu_opcode_92)
MAKE_CPU_TEST("../tests/v1/cb e9.json",cpu_opcode_CBE9)
MAKE_CPU_TEST("../tests/v1/7a.json",cpu_opcode_7A)
MAKE_CPU_TEST("../tests/v1/cb d6.json",cpu_opcode_CBD6)
MAKE_CPU_TEST("../tests/v1/cb 47.json",cpu_opcode_CB47)
MAKE_CPU_TEST("../tests/v1/a4.json",cpu_opcode_A4)
MAKE_CPU_TEST("../tests/v1/cb fc.json",cpu_opcode_CBFC)
MAKE_CPU_TEST("../tests/v1/cb 48.json",cpu_opcode_CB48)
MAKE_CPU_TEST("../tests/v1/06.json",cpu_opcode_06)
MAKE_CPU_TEST("../tests/v1/cb c0.json",cpu_opcode_CBC0)
MAKE_CPU_TEST("../tests/v1/b8.json",cpu_opcode_B8)
MAKE_CPU_TEST("../tests/v1/cb 00.json",cpu_opcode_CB00)
MAKE_CPU_TEST("../tests/v1/6d.json",cpu_opcode_6D)
MAKE_CPU_TEST("../tests/v1/cb 2d.json",cpu_opcode_CB2D)
MAKE_CPU_TEST("../tests/v1/cb 43.json",cpu_opcode_CB43)
MAKE_CPU_TEST("../tests/v1/cb 3b.json",cpu_opcode_CB3B)
MAKE_CPU_TEST("../tests/v1/cb 20.json",cpu_opcode_CB20)
MAKE_CPU_TEST("../tests/v1/cb 13.json",cpu_opcode_CB13)
MAKE_CPU_TEST("../tests/v1/cb 8e.json",cpu_opcode_CB8E)
MAKE_CPU_TEST("../tests/v1/cb db.json",cpu_opcode_CBDB)
MAKE_CPU_TEST("../tests/v1/fa.json",cpu_opcode_FA)
MAKE_CPU_TEST("../tests/v1/52.json",cpu_opcode_52)
MAKE_CPU_TEST("../tests/v1/34.json",cpu_opcode_34)
MAKE_CPU_TEST("../tests/v1/cb bb.json",cpu_opcode_CBBB)
MAKE_CPU_TEST("../tests/v1/2b.json",cpu_opcode_2B)
MAKE_CPU_TEST("../tests/v1/cb af.json",cpu_opcode_CBAF)
MAKE_CPU_TEST("../tests/v1/bb.json",cpu_opcode_BB)
MAKE_CPU_TEST("../tests/v1/a1.json",cpu_opcode_A1)
MAKE_CPU_TEST("../tests/v1/cb eb.json",cpu_opcode_CBEB)
MAKE_CPU_TEST("../tests/v1/5b.json",cpu_opcode_5B)
